### ISSUE TITLE
test backend with docker

### ISSUE THREAD

**Issue by sarahfeichtinger** [primetzvan/minutiae#11]

**Comment by primetzvan** [comment]
- mosquitto works with an older version (listener on newer ones creates a bug) -> 1.6.15 works
- frontend works 
- database works on port 4001
- backend debugging is in progress

**Comment by primetzvan** [comment]
- Backend works -> it was an issue with the connection between mqtt and the backend
       - Solution: write dockername instead of localhost
- Mosquitto works
